import type { McpServer } from "./types";

export const servers: McpServer[] = [
  {
    id: "deepwiki",
    name: "deepwiki",
    authType: "public",
    description: "DeepWiki — AI-документация для GitHub-репозиториев",
    path: "/mcp/dev/deepwiki",
    status: { kind: "success" },
    mcpCommand: {
      command: "npx",
      args: ["-y", "@anthropic/deepwiki-mcp"],
      env: { GITHUB_PERSONAL_ACCESS_TOKEN: "YOUR_TOKEN_HERE" },
    },
    tools: [
      { name: "read_wiki_structure", description: "Получить список тем документации для GitHub-репозитория. Args: `repoName` — репозиторий в формате owner/repo.", category: "Чтение" },
      { name: "read_wiki_contents", description: "Просмотреть документацию GitHub-репозитория. Args: `repoName` — репозиторий в формате owner/repo.", category: "Чтение" },
      { name: "ask_question", description: "Задать вопрос о репозитории и получить ответ с помощью ИИ. Args: `repoName` — репозиторий в формате owner/repo, `question` — текст вопроса.", category: "Генерация" },
    ],
  },
  {
    id: "test",
    name: "test",
    authType: "keycloak",
    description: "MCP Server Everything — демонстрационные инструменты",
    path: "/mcp/test",
    status: { kind: "success" },
    mcpCommand: {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-everything"],
    },
    tools: [
      { name: "echo", description: "Возвращает входное сообщение обратно. Args: `message` — текст для эхо.", category: "Утилиты" },
      { name: "add", description: "Складывает два числа. Args: `a` — первое число, `b` — второе число.", category: "Утилиты" },
      { name: "longRunningOperation", description: "Запускает длительную операцию с прогрессом. Args: `duration` — длительность в секундах, `steps` — количество шагов.", category: "Утилиты" },
      { name: "printEnv", description: "Выводит переменные окружения сервера.", category: "Утилиты" },
      { name: "sampleLLM", description: "Запрашивает LLM-модель для генерации текста. Args: `prompt` — промпт, `maxTokens` — макс. токенов.", category: "Генерация" },
      { name: "getTinyImage", description: "Возвращает маленькое тестовое изображение.", category: "Ресурсы" },
      { name: "annotatedMessage", description: "Возвращает аннотированное сообщение с метаданными. Args: `messageType` — тип сообщения, `includeImage` — включить изображение.", category: "Генерация" },
      { name: "getResourceReference", description: "Возвращает ссылку на ресурс. Args: `resourceId` — идентификатор ресурса.", category: "Ресурсы" },
      { name: "createTextResource", description: "Создаёт текстовый ресурс. Args: `name` — имя, `content` — содержимое.", category: "Создание" },
      { name: "listResourceTemplates", description: "Получить список шаблонов ресурсов.", category: "Ресурсы" },
      { name: "readResource", description: "Прочитать содержимое ресурса. Args: `uri` — URI ресурса.", category: "Чтение" },
      { name: "listPrompts", description: "Получить список доступных промптов.", category: "Чтение" },
      { name: "getPrompt", description: "Получить конкретный промпт. Args: `name` — имя промпта.", category: "Чтение" },
    ],
  },
  {
    id: "rag-search",
    name: "rag-search",
    authType: "keycloak",
    description: "RAG Search MCP — поиск по корпоративным базам знаний",
    path: "/mcp/rag-search",
    status: { kind: "success" },
    mcpCommand: {
      command: "npx",
      args: ["-y", "@erc3/rag-search-mcp"],
    },
    tools: [
      { name: "rag_auth", description: "Авторизация в RAG-сервисе. Args: `token` — токен доступа.", category: "Утилиты" },
      { name: "rag_collection_create", description: "Создать коллекцию документов. Args: `name` — название, `description` — описание.", category: "Создание" },
      { name: "rag_collection_list", description: "Получить список коллекций.", category: "Чтение" },
      { name: "rag_collection_delete", description: "Удалить коллекцию. Args: `collectionId` — идентификатор.", category: "Утилиты" },
      { name: "rag_document_upload", description: "Загрузить документ в коллекцию. Args: `collectionId` — ID коллекции, `fileUrl` — URL файла.", category: "Создание" },
      { name: "rag_document_list", description: "Получить список документов в коллекции. Args: `collectionId` — идентификатор.", category: "Чтение" },
      { name: "rag_search", description: "Семантический поиск по документам. Args: `query` — поисковый запрос, `collectionId` — ID коллекции, `topK` — кол-во результатов.", category: "Генерация" },
      { name: "rag_search_multi", description: "Поиск по нескольким коллекциям. Args: `query` — запрос, `collectionIds` — массив ID.", category: "Генерация" },
      { name: "rag_chunk_list", description: "Получить чанки документа. Args: `documentId` — ID документа.", category: "Чтение" },
      { name: "rag_reindex", description: "Переиндексировать коллекцию. Args: `collectionId` — идентификатор.", category: "Утилиты" },
    ],
  },
  {
    id: "google-workspace",
    name: "google-workspace",
    authType: "keycloak",
    description: "Google Workspace MCP — Gmail, Calendar, Drive, Docs",
    path: "/mcp/google-workspace",
    status: { kind: "success" },
    mcpCommand: {
      command: "npx",
      args: ["-y", "@anthropic/google-workspace-mcp"],
    },
    tools: [
      { name: "search_gmail_messages", description: "Поиск писем в Gmail по запросу. Args: `query` — поисковый запрос, `maxResults` — макс. кол-во результатов.", category: "Чтение" },
      { name: "send_gmail_message", description: "Отправить письмо через Gmail. Args: `to` — адресат, `subject` — тема, `body` — текст письма.", category: "Создание" },
      { name: "get_gmail_message", description: "Получить письмо по ID. Args: `messageId` — идентификатор письма.", category: "Чтение" },
      { name: "list_gmail_labels", description: "Получить список лейблов Gmail.", category: "Чтение" },
      { name: "create_gmail_draft", description: "Создать черновик в Gmail. Args: `to` — адресат, `subject` — тема, `body` — текст.", category: "Создание" },
      { name: "list_calendar_events", description: "Получить события из Google Calendar. Args: `calendarId` — ID календаря, `timeMin` — начало, `timeMax` — конец.", category: "Чтение" },
      { name: "create_calendar_event", description: "Создать событие в календаре. Args: `summary` — название, `start` — начало, `end` — конец, `attendees` — участники.", category: "Создание" },
      { name: "search_drive_files", description: "Поиск файлов в Google Drive. Args: `query` — запрос.", category: "Чтение" },
      { name: "get_drive_file", description: "Получить содержимое файла из Drive. Args: `fileId` — ID файла.", category: "Чтение" },
      { name: "create_drive_file", description: "Создать файл в Google Drive. Args: `name` — имя файла, `mimeType` — тип, `content` — содержимое.", category: "Создание" },
      { name: "list_drive_files", description: "Получить список файлов в Drive. Args: `folderId` — ID папки.", category: "Чтение" },
      { name: "get_document", description: "Получить содержимое Google Doc. Args: `documentId` — ID документа.", category: "Чтение" },
      { name: "create_document", description: "Создать Google Doc. Args: `title` — заголовок, `content` — текст.", category: "Создание" },
      { name: "update_document", description: "Обновить Google Doc. Args: `documentId` — ID документа, `content` — новый текст.", category: "Создание" },
      { name: "get_spreadsheet", description: "Получить данные из Google Sheets. Args: `spreadsheetId` — ID, `range` — диапазон.", category: "Чтение" },
      { name: "update_spreadsheet", description: "Обновить ячейки в Sheets. Args: `spreadsheetId` — ID, `range` — диапазон, `values` — данные.", category: "Создание" },
      // Additional tools represented by count (138 total implied)
      ...Array.from({ length: 122 }, (_, i) => ({
        name: `gw_tool_${i + 17}`,
        description: `Google Workspace инструмент #${i + 17}.`,
        category: ["Чтение", "Создание", "Утилиты", "Генерация"][i % 4],
      })),
    ],
  },
  {
    id: "text2sql",
    name: "text2sql",
    authType: "keycloak",
    description: "Text2SQL MCP — естественный язык в SQL-запросы",
    path: "/mcp/text2sql",
    status: { kind: "success" },
    mcpCommand: {
      command: "npx",
      args: ["-y", "@erc3/text2sql-mcp"],
    },
    tools: [
      { name: "connect", description: "Подключиться к базе данных. Args: `connectionString` — строка подключения.", category: "Утилиты" },
      { name: "pg_query", description: "Выполнить SQL-запрос. Args: `sql` — SQL-выражение, `params` — параметры запроса.", category: "Чтение" },
      { name: "pg_explain", description: "Получить план выполнения запроса. Args: `sql` — SQL-выражение.", category: "Чтение" },
      { name: "list_tables", description: "Получить список таблиц в БД.", category: "Чтение" },
      { name: "describe_table", description: "Описание структуры таблицы. Args: `tableName` — имя таблицы.", category: "Чтение" },
    ],
  },
  {
    id: "speechcore",
    name: "speechcore",
    authType: "keycloak",
    description: "SpeechCore AI STT MCP (SSE) — транскрипция и распознавание речи",
    path: "/mcp/speechcore",
    status: { kind: "success" },
    mcpCommand: {
      command: "npx",
      args: ["-y", "@erc3/speechcore-mcp"],
    },
    tools: [
      { name: "transcribe", description: "Запустить транскрипцию аудиофайла. Args: `audioUrl` — URL аудио, `language` — язык распознавания.", category: "Генерация" },
      { name: "get_transcription_status", description: "Проверить статус транскрипции. Args: `taskId` — идентификатор задачи.", category: "Чтение" },
      { name: "list_transcriptions", description: "Получить список всех транскрипций.", category: "Чтение" },
    ],
  },
  {
    id: "atlassian",
    name: "atlassian",
    authType: "keycloak",
    description: "Atlassian MCP — Jira и Confluence",
    path: "/mcp/atlassian",
    mcpCommand: {
      command: "npx",
      args: ["-y", "@anthropic/atlassian-mcp"],
    },
    status: {
      kind: "auth",
      fields: [
        { label: "Atlassian Username", placeholder: "user@company.com" },
        { label: "Jira API Token", placeholder: "Jira API Token", type: "password" },
        { label: "Confluence API Token", placeholder: "Confluence API Token", type: "password" },
      ],
    },
    tools: [],
  },
  {
    id: "erc3-store",
    name: "erc3-store",
    authType: "keycloak",
    description: "ERC3 Store MCP — управление хранилищем данных",
    path: "/mcp/erc3/store",
    status: { kind: "error", message: "DNS resolution failed: getaddrinfo ENOTFOUND erc3-store.internal" },
    tools: [],
  },
  {
    id: "eval-store",
    name: "eval-store",
    authType: "keycloak",
    description: "Eval Store MCP — хранилище результатов оценки моделей",
    path: "/mcp/eval-store",
    status: { kind: "error", message: "DNS resolution failed: getaddrinfo ENOTFOUND eval-store.internal" },
    tools: [],
  },
];
